package com.fmi.oopjava.clientSide;

import com.fmi.oopjava.enums.ClientNotifications;
import com.fmi.oopjava.cardValidator.CardNumberValidator;
import com.fmi.oopjava.client.Client;
import com.fmi.oopjava.interfaces.RemoteServer;
import com.fmi.oopjava.bankCard.BankCard;
import com.fmi.oopjava.xmlSerializor.Storer;
import java.rmi.RemoteException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.SwingUtilities;

/**
 *
 * @author Dimitar
 */
public class TokenizationPanel extends javax.swing.JPanel {

    /**
     * Creates new form TestPanel
     */
    public TokenizationPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblGreetings = new javax.swing.JLabel();
        txtEnterCardNumber = new javax.swing.JTextField();
        txtGeneratedToken = new javax.swing.JTextField();
        btnGenerateToken = new javax.swing.JButton();
        lblCardNumber = new javax.swing.JLabel();
        lblGeneratedToken = new javax.swing.JLabel();
        txtEnterToken = new javax.swing.JTextField();
        btnGetCardNumber = new javax.swing.JButton();
        txtGetCardNumber = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lblReceivedCardNumber = new javax.swing.JLabel();
        lblNotifications = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();

        lblGreetings.setForeground(new java.awt.Color(0, 150, 0));
        lblGreetings.setText(" ");

        btnGenerateToken.setText("<- Generate Token ->");
        btnGenerateToken.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateTokenActionPerformed(evt);
            }
        });

        lblCardNumber.setText("Enter card number:");

        lblGeneratedToken.setText("Generated Token:");

        btnGetCardNumber.setText("<- Get card number ->");
        btnGetCardNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetCardNumberActionPerformed(evt);
            }
        });

        jLabel1.setText("Enter token:");

        lblReceivedCardNumber.setText("Received card number:");

        lblNotifications.setForeground(new java.awt.Color(250, 0, 0));
        lblNotifications.setText(" ");

        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblGreetings, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addComponent(lblNotifications, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(94, 94, 94)
                        .addComponent(btnLogout))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblReceivedCardNumber))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCardNumber)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblGeneratedToken))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(txtEnterToken, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnGetCardNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(txtEnterCardNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnGenerateToken, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtGeneratedToken, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                            .addComponent(txtGetCardNumber))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNotifications)
                    .addComponent(lblGreetings)
                    .addComponent(btnLogout))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCardNumber)
                    .addComponent(lblGeneratedToken))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEnterCardNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGenerateToken)
                    .addComponent(txtGeneratedToken, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(9, 9, 9))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblReceivedCardNumber)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEnterToken, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGetCardNumber)
                    .addComponent(txtGetCardNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        try {
            init();
            server.serializeObject(client);
            server.logout(client);
            client = null;
            frame = (MainFrame) SwingUtilities.getWindowAncestor(this);
            frame.changePanel(this, new LoginPanel());
        } catch (RemoteException ex) {
            Logger.getLogger(TokenizationPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnGenerateTokenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateTokenActionPerformed
        String cardNumber = txtEnterCardNumber.getText();
        if (!CardNumberValidator.isValid(cardNumber)) {
            lblNotifications.setText(ClientNotifications.INVALID_CARD_NUMBER.getMessage());
        } else {
            try {
                init();
                lblNotifications.setText(ClientNotifications.TOKENIZATION_SUCCESSFULL.getMessage());
                
                BankCard card = (BankCard) server.deserializeObject(cardNumber, BankCard.class);
                if (card == null) {
                    card = new BankCard(cardNumber);
                    server.serializeObject(card);
                }
                else if(card != null && !client.hasCard(cardNumber)){
                    lblNotifications.setText("This is not your card!");
                    return;
                }
                if (!client.hasCard(cardNumber)) {
                    client.addCard(cardNumber);
                }
                
                String token = server.generateToken(cardNumber);
                txtGeneratedToken.setText(token);
                card.addToken(token);
                server.serializeObject(card);
                
            } catch (RemoteException ex) {
                Logger.getLogger(TokenizationPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnGenerateTokenActionPerformed

    private void btnGetCardNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetCardNumberActionPerformed
        String token = txtEnterToken.getText();
        try {
            init();
            String cardNumber = server.getCardNumber(token);
            if (cardNumber != null) {
                txtGetCardNumber.setText(cardNumber);
                lblNotifications.setText(ClientNotifications.CARD_FOUND.getMessage());
            } else {
                lblNotifications.setText(ClientNotifications.NO_TOKEN.getMessage());
            }
        } catch (RemoteException ex) {
            Logger.getLogger(TokenizationPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnGetCardNumberActionPerformed
    
    private MainFrame frame;
    private RemoteServer server;
    private Client client = null;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerateToken;
    private javax.swing.JButton btnGetCardNumber;
    private javax.swing.JButton btnLogout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblCardNumber;
    private javax.swing.JLabel lblGeneratedToken;
    private javax.swing.JLabel lblGreetings;
    private javax.swing.JLabel lblNotifications;
    private javax.swing.JLabel lblReceivedCardNumber;
    private javax.swing.JTextField txtEnterCardNumber;
    private javax.swing.JTextField txtEnterToken;
    private javax.swing.JTextField txtGeneratedToken;
    private javax.swing.JTextField txtGetCardNumber;
    // End of variables declaration//GEN-END:variables

    public void setClient(Client c) {
        client = c;
        setGreetings(c.getName());
    }
    
    private void init() {
        frame = (MainFrame) SwingUtilities.getWindowAncestor(this);
        server = frame.getServer();
    }
    
    private void setGreetings(String name) {
        lblGreetings.setText(String.format("Hello, %s!", name));
    }
}
